### ISSUE TITLE
一个小的翻译问题

### ISSUE THREAD

**Issue by sarendis56** [xiaoweiChen/Learn-LLVM-17#1]
最新版本第39页，方框内容的标题为“递归下降解析器不能从语法中构造出来”，原文为“A recursive descent parser can’t be constructed from every grammar”，漏翻了"every"，应为“并不是所有语法都可以用于构造递归下降解析器”。

**Comment by sarendis56** [comment]
同一页稍下一部分第二段第二行“结果是只需要两个类来记录信息”，“The result is that only a couple of classes are required to record the information”。这里上下文可以看出明显不是两个，“a couple of”意思是若干个

**Comment by sarendis56** [comment]
第29页语法框下面两行：
`是规则左右两边之间的分隔符，” with”、” 和”:” 是表示这个字符串的标记`
原文：
`Here, "with", "," and ":" are tokens that represent this string.`
少了一组`,"`

**Comment by sarendis56** [comment]
第44页中间第二条：`下面的构造定义了一个常量，保存 a 和空字节作为 C中的字符串结束符:` 这里的翻译有点歧义，原文为`holding a and the null byte used as a string terminator in C`，`used as a string terminator in C` 修饰的是null byte而不是a和null byte整体，可以翻译为`保存 a 和作为 C中字符串结束符的空字节`

**Comment by sarendis56** [comment]
第46页第8点的第一句好像是重复打了一句第7点的代码，可以直接删掉

**Comment by xiaoweiChen** [comment]
嗯，感谢勘误哈。
可以直接提PR过来，然后再PR里面加上comment，这样更直接一些
