### ISSUE TITLE
所有翻译的文档，可不可以做一份epub格式

### ISSUE THREAD

**Issue by hggq** [xiaoweiChen/Learn-LLVM-17#4]
翻译的非常不错，谢谢能这样坚持。
现在感觉所有翻译成果都使用pdf，有时候手机看，或者MacOS看，背景不能为黑色。
如果多导出为epub一份也不错。
我试着配置环境，不熟悉导出不成功。
希望能提供一份epub格式，这样可以调节大小阅读。

就是之前历史的翻译的书也提供一份epub格式。

**Comment by xiaoweiChen** [comment]
嗯，因为我自己很少用手机或者MacOS看，多数时间都是用笔记本或者pad看，所以PDF对于我自己来说已经足够了。

不过对于所有翻译的文档都出一份epub，这个可能实难做到，这个工作量有些大的。markdown格式的貌似有办法直接转，可以网上搜一下方法。需要epub的话，可能就要自己配一下环境来生成了。至于epub的格式，我需要研究一下。看看xelatex能不能直接生成，如果我找到方法了会共享出来。

我会考虑后续的翻译中，添加提供epub文档。

**Comment by xiaoweiChen** [comment]
有在线pdf转epub的网站，可以试试看 https://www.freefileconvert.com/

**Comment by xiaoweiChen** [comment]
[How to convert LaTeX document into Epub file using Python](https://medium.com/@diegodelagos/how-to-convert-latex-document-into-epub-files-using-python-e365437499ee)

**Comment by xiaoweiChen** [comment]
做了些测试PDF转EPUB后，页面布局的效果不是很好。
从Latex转的话，需要用到pandoc，用类似下面的命令就可以
```
.\pandoc.exe -f latex -t epub main.tex -o Main.epub
```
但pandoc无法识别用\NewDocumentCommand定义的函数。
你需要修改主tex将函数实现在原始位置重新展开，这样再用pandoc生成epub应该就可以了。

**Comment by hggq** [comment]
我配置了环境，不知道怎么使用，就是安装6G多那个。
epub格式 macos 使用比较方便，可以做笔记之类，背景可以黑色

**Comment by xiaoweiChen** [comment]
嗯，就你的需求来看，我个人觉得你没有必要去折腾tex live和latex的源码。只是需要找到一款可以将文档背景修改成黑色，并且能做笔记的PDF阅读器即可。

我个人推荐 福昕阅读器，Windows版做笔记也是可以的。其也支持MacOS，可以试一试。阅读器的[夜间模式](https://www.foxitsoftware.cn/pdf-reader-plus/news/1482.html)

或者是使用PDF的编辑器，比如，Adobe 或 [福昕PDF编辑器](https://www.foxitsoftware.cn/pdfbianji/news/4341.html)，将文档背景调成黑色，文字为白色。

~~Readme里面的配置环境是针对Windows的，我在Linux下也使用过tex live，但没有在MacOS下用过tex live。根据经验，估计和MacOS中一样，直接使用命令行就可以了。~~
```
xelatex -synctex=1 -interaction=nonstopmode -shell-escape -8bit "Learn-LLVM-17".tex
```
